name: Django CI

on:
  push:
    branches:
      - main  # Run the workflow on push to the `main` branch.
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to the `main` branch.

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use Python version 3.9 (adjust as needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Set up database
        run: |
          sudo apt-get install -y libpq-dev  # Install dependencies for PostgreSQL if using PostgreSQL

      - name: Run migrations
        run: |
          python manage.py migrate  # Run database migrations

      - name: Run tests
        run: |
          python manage.py test  # Run Django tests
