name: Django CI

on:
  push:
    branches:
      - main  # Run the workflow on push to the `main` branch.
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to the `main` branch.

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python (Use Python 3.9)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 4: Set up PostgreSQL dependencies (if using PostgreSQL)
      - name: Set up PostgreSQL
        run: |
          sudo apt-get install -y libpq-dev  # Install PostgreSQL dependencies for Python

      # Step 5: Set up the database (optional step for PostgreSQL users)
      - name: Set up database
        run: |
          sudo service postgresql start  # Start PostgreSQL service (if you're using PostgreSQL)
          sudo -u postgres psql -c "CREATE DATABASE test_db;"  # Create a test database

      # Step 6: Run migrations
      - name: Run migrations
        run: |
          python manage.py migrate  # Apply migrations to the test database

      # Step 7: Run tests
      - name: Run tests
        run: |
          python manage.py test  # Run Django tests (ensure tests are properly set up)
